title: "NNCOTR"
description: "This is a documentation for NNCOTR"
theme: jekyll-theme-architect  # 使用 Architect 主题
markdown: kramdown
kramdown:
  math_engine: mathjax  # 启用数学公式
  toc: true             # 自动生成目录
