title: "我的项目网站"
description: "这是一个基于 Architect 主题的 GitHub Pages 网站"
theme: jekyll-theme-architect  # 使用 Architect 主题
markdown: kramdown
kramdown:
  math_engine: mathjax  # 启用数学公式
  toc: true             # 自动生成目录
